version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: "mongo"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    command: bash -c "mongoimport --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env.sample
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
